org = "rust-lang"
name = "project-goal-reference-expansion"
description = "Project Goal coordination repository for expansion of the Rust Reference"
homepage = "https://github.com/rust-lang/rust-project-goals/blob/main/src/2025h2/reference-expansion.md"
bots = []

[access.teams]
lang-docs = "write"

[access.individuals]
joshtriplett = "maintain"
jackh726 = "maintain"
Amanieu = "write"
GuillaumeGomez = "write"
SparrowLii = "write"
borsakv = "write"
epage = "write"
lcnr = "write"
lucarlig = "write"
m-ou-se = "write"
midiareshadi = "write"
petrochenkov = "write"
yaahc = "write"
